name: Deploy to MAIN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: 3.109.5.168
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "." # Adjust this to the path of your Node.js app's files
          target: "/home/ubuntu/myapp" # Adjust this to the destination path on the EC2 instance

      - name: SSH into EC2 and deploy with PM2
        uses: appleboy/ssh-action@master
        with:
          host: 3.109.5.168
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 2m
          script: |
